# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barba's blog
email: mlafroce@gmail.com
description: A blog with tutorials and stuff I find over the web.
baseurl: ""
url: https://mlafroce.github.io
#url: http://localhost:4000

social:
  github: mlafroce
  linkedin: matias-lafroce
  lastfm: matiasz123
  rss: feed.xml

disqus: barbablog

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

# Default settings

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      disquscomments: false
      fbcomments: true
      fblike: true